# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x11photo.analyzer.v1\";\n\x13\x41nalyzePhotoRequest\x12\x10\n\x08photo_id\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t\"l\n\x14\x41nalyzePhotoResponse\x12\x13\n\x0b\x66\x61\x63\x65s_count\x18\x01 \x01(\x05\x12\x12\n\nis_blurred\x18\x02 \x01(\x08\x12\x12\n\nblur_score\x18\x03 \x01(\x01\x12\x17\n\x0fperceptual_hash\x18\x04 \x01(\t2p\n\rPhotoAnalyzer\x12_\n\x0c\x41nalyzePhoto\x12&.photo.analyzer.v1.AnalyzePhotoRequest\x1a\'.photo.analyzer.v1.AnalyzePhotoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEPHOTOREQUEST']._serialized_start=37
  _globals['_ANALYZEPHOTOREQUEST']._serialized_end=96
  _globals['_ANALYZEPHOTORESPONSE']._serialized_start=98
  _globals['_ANALYZEPHOTORESPONSE']._serialized_end=206
  _globals['_PHOTOANALYZER']._serialized_start=208
  _globals['_PHOTOANALYZER']._serialized_end=320
# @@protoc_insertion_point(module_scope)
